[matrix.windows]
runner = 'windows-latest'

[[matrix.windows.config]]
arch = 'x86'

[[matrix.windows.config]]
arch = 'x64'
vs_arch = 'amd64'

[[matrix.windows.config]]
arch = 'x86'
debugrec = true

[matrix.linux]
runner = 'ubuntu-20.04'

[[matrix.linux.config]]
arch = 'x64'
include-groups = true

[[matrix.linux.config]]
arch = 'x64'
debugrec = true

[matrix.mac]
runner = 'macos-13'

[[matrix.mac.config]]
arch = 'x64'
