[groups.'System.c4g']
parts = [
    'continuous-v335',
    'continuous-v336',
    'continuous-v337',
    'continuous-v338',
    'continuous-v339',
    'continuous-v340',
    'v341',
    'v343',
    'v344',
    'v345',
    'v346',
    'v347',
    'v349',
    'v352',
    'v353',
    'v356',
    'v359',
]

[groups.'Graphics.c4g']
parts = [
    'continuous-v335',
    'continuous-v336',
    'continuous-v339',
    'v341',
    'v343',
    'v347',
    'v349',
    'v352',
    'v353',
    'v356',
    'v359',
]

[groups.content]
parts = [
    'lc_49108.zip',
    'lc_49109.zip',
    'lc_491010.zip',
    'lc_491011.zip',
    'lc_491012.zip',
    'lc_491013.zip',
    'lc_491014.zip',
    'lc_491015.zip',
]

[matrix.windows]
runner = 'windows-latest'

#[[matrix.windows.config]]
#arch = 'x86'

[[matrix.windows.config]]
arch = 'x64'
vs_arch = 'amd64'

#[[matrix.windows.config]]
#arch = 'x86'
#debugrec = true

[matrix.linux]
runner = 'ubuntu-20.04'

[[matrix.linux.config]]
arch = 'x64'
include-groups = true

#[[matrix.linux.config]]
#arch = 'x64'
#debugrec = true

#[matrix.mac]
#runner = 'macos-13'

#[[matrix.mac.config]]
#arch = 'x64'
