name: Build Binaries

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      runner:
        type: string
        required: true
      arch:
        type: string
        required: true
      debugrec:
        type: boolean
        required: true
      include-groups:
        type: boolean
        required: true
    outputs:
      engine-artifact-id:
        description: "The artifact ID of the engine binaries"
        value: ${{ jobs.build-binaries.outputs.engine-artifact-id }}
      c4group-artifact-id:
        description: "The artifact ID of the c4group binaries"
        value: ${{ jobs.build-binaries.outputs.c4group-artifact-id }}

defaults:
  run:
    shell: bash

jobs:
  build-binaries:
    name: Build Binaries
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.runner }}
    outputs:
      engine-artifact-id: ${{ steps.publish-engine.outputs.artifact_id }}
      c4group-artifact-id: ${{ steps.publish-c4group.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Setup Directories"
        run: mkdir output

      - name: "Configure Platform"
        run: |
          echo "CONFIG_SUFFIX=${{ inputs.os }}-${{ inputs.arch }}" >> $GITHUB_ENV
          autobuild/${{ inputs.os }}.sh

      - name: "Configure Platform Architecture"
        run: |
          autobuild/${{ inputs.os }}-${{ inputs.arch }}.sh

      - name: "Linux: Setup"
        if: ${{ inputs.os == 'Linux' }}
        run: $CHROOT autobuild/setup_linux.sh

      - name: "Mac: Work around libpng mess"
        if: ${{ inputs.os == 'Mac' }}
        run: sudo rm -r /Library/Frameworks/Mono.framework/Headers

      - name: "Windows: Setup VS Dev Environment"
        if: ${{ inputs.os == 'Windows' }}
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
        with:
          arch: ${{ env.VS_ARCH }}

      - name: "Dependencies"
        run: |
          mkdir deps
          cd deps
          curl -L https://github.com/legacyclonk/deps/releases/download/2024-07-24/lc_deps-$CONFIG_SUFFIX.tar.gz | tar -xz
          ./fix_paths.sh

      - name: Configure
        run: |
          $CHROOT cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_TESTS=On -DCMAKE_CTEST_ARGUMENTS=--output-on-failure $CMAKE_CONFIGURE_ARGS

      - name: "Enable Debugrec"
        if: ${{ inputs.debugrec }}
        run: |
          cmake -B build -DDEBUGREC=On
          echo "CONFIG_SUFFIX=${{ inputs.os }}-${{ inputs.arch }}-debugrec" >> $GITHUB_ENV

      - name: "Disable PCH"
        if: ${{ inputs.debugrec && inputs.os == 'Linux' }}
        run: |
          cmake -B build -DUSE_PCH=Off

      - name: Build
        run: |
          $CHROOT cmake --build build $CMAKE_BUILD_ARGS

      - name: Test
        run: |
          $CHROOT cmake --build build --target test

      - name: "Windows: Collect binaries"
        if: ${{ inputs.os == 'Windows' }}
        run: |
          cd build
          mv *.{exe,pdb} ../output

      - name: "Linux: Collect binaries"
        if: ${{ inputs.os == 'Linux' }}
        run: |
          cd build
          cp clonk c4group ../output

      - name: "Linux: Create AppImage"
        if: ${{ inputs.os == 'Linux' }}
        run: |
          tools/make_AppImage.sh

      - name: "Mac: Create Bundle"
        if: ${{ inputs.os == 'Mac' }}
        run: |
          cd build
          DESTDIR=inst ninja install
          mv inst/usr/local/c4group inst/usr/local/clonk.app ../output

      - name: "Publish Engine"
        id: publish-engine
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONFIG_SUFFIX }}
          path: output/clonk*

      - name: "Publish c4group"
        id: publish-c4group
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONFIG_SUFFIX }}-c4group
          path: output/c4group*

      - name: "Build c4gs"
        if: ${{ inputs.include-groups }}
        run: |
          C4GROUP=$PWD/build/c4group tools/make_Graphics.c4g.sh
          C4GROUP=$PWD/build/c4group tools/make_System.c4g.sh

      - name: "Publish System.c4g"
        if: ${{ inputs.include-groups }}
        uses: actions/upload-artifact@v4
        with:
          name: System.c4g
          path: System.c4g

      - name: "Publish Graphics.c4g"
        if: ${{ inputs.include-groups }}
        uses: actions/upload-artifact@v4
        with:
          name: Graphics.c4g
          path: Graphics.c4g
