name: Autobuild

on:
  push:
    branches-ignore: 'build-test*'
    tags-ignore: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  Autobuild:
    uses: './.github/workflows/build.yml'
