name: Autobuild

on:
  push:
    branches-ignore: 'build-test*'
    tags: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  Autobuild:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            arch: x64
            env: Mac
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Setup Directories"
        run: mkdir output

      - name: "Configure Platform"
        run: |
          echo "CONFIG_SUFFIX=${{ matrix.env }}-${{ matrix.arch }}" >> $GITHUB_ENV
          autobuild/${{ matrix.env }}.sh

      - name: "Configure Platform Architecture"
        run: |
          autobuild/${{ matrix.env }}-${{ matrix.arch }}.sh

      - name: "Mac: Work around libpng mess"
        if: ${{ matrix.env == 'Mac' }}
        run: sudo rm -r /Library/Frameworks/Mono.framework/Headers
      
      - name: "Mac: Install gcc"
        if: ${{ matrix.env == 'Mac' }}
        run: brew install gcc
      
      - name: "Dependencies"
        run: |
          mkdir deps
          cd deps
          curl -L https://github.com/legacyclonk/deps/releases/download/2022-10-24/lc_deps-$CONFIG_SUFFIX.tar.gz | tar -xz
          ./fix_paths.sh

      - name: Configure
        run: |
          $CHROOT cmake -B build . $CMAKE_CONFIGURE_ARGS

      - name: "Enable Debugrec"
        if: ${{ matrix.config == 'Debugrec' }}
        run: |
          cmake -B build -DDEBUGREC=On
          echo "CONFIG_SUFFIX=${{ matrix.env }}-${{ matrix.arch }}-debugrec" >> $GITHUB_ENV

      - name: Build
        run: |
          $CHROOT cmake --build build $CMAKE_BUILD_ARGS

      - name: "Mac: Create Bundle"
        if: ${{ matrix.env == 'Mac' }}
        run: |
          cd build
          make DESTDIR=inst install
          mv inst/usr/local/c4group inst/usr/local/clonk.app ../output

      - name: "Publish Main Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CONFIG_SUFFIX }}
          path: output/*

      - name: "Pack: Mac"
        if: ${{ matrix.env == 'Mac' }}
        run: |
          cd output
          zip -r LegacyClonk-$CONFIG_SUFFIX.zip *
