name: Release
on:
  push:
    tags:
      - '*'
    branches:
      - '*'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-ci-config:
    name: Generate CI Configuration
    uses: './.github/workflows/ci-config.yml'

  build:
    needs: [generate-ci-config]
    uses: './.github/workflows/build.yml'
    with:
      matrix: ${{ needs.generate-ci-config.outputs.matrix }}

  build-content:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/content

      - uses: actions/download-artifact@v4
        with:
          name: Linux-x64-c4group
      - run: ls -R

