name: Release
on:
  push:
    tags:
      - '*'
    branches:
      - '*'

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-ci-config:
    name: Generate CI Configuration
    uses: './.github/workflows/ci-config.yml'

  build-binaries:
    name: Build Binaries
    needs: [generate-ci-config]
    uses: './.github/workflows/build.yml'
    with:
      matrix: ${{ needs.generate-ci-config.outputs.matrix }}

  build-content:
    name: Content
    runs-on: windows-latest
    needs: [generate-ci-config, build-binaries]
    env:
      C4GROUP: ../c4group.exe
      LC_GROUPS: ${{ needs.generate-ci-config.outputs.groups }}
      OBJVERSION: ${{ needs.generate-ci-config.outputs.objversion }}
      VERSION: ${{ needs.generate-ci-config.outputs.buildversion }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            autobuild
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/content
          path: content

      - uses: actions/download-artifact@v4
        with:
          name: c4group-Windows-x64

      - name: Create output directory
        run: New-Item -Path content/output -ItemType Directory

      - name: Pack groups & create updates
        run: |
          Set-Location content
          ../autobuild/MakeContentGroupsAndUpdateGroups.ps1 -OutDir output

      - name: Publish content
        uses: actions/upload-artifact@v4
        with:
          name: content
          path: content/output/*.c4[dgf]

      - name: Publish content updates
        uses: actions/upload-artifact@v4
        with:
          name: content-updates
          path: content/output/*.c4[dgf].c4u

  build-system-graphics-updates:
    name: "Update Groups: System.c4g & Graphics.c4g"
    runs-on: windows-latest
    needs: [generate-ci-config, build-binaries]
    env:
      C4GROUP: ./c4group.exe
      LC_GROUPS: ${{ needs.generate-ci-config.outputs.groups }}
      OBJVERSION: ${{ needs.generate-ci-config.outputs.objversion }}
      VERSION: ${{ needs.generate-ci-config.outputs.buildversion }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            autobuild

      - uses: actions/download-artifact@v4
        with:
          name: System.c4g
      - uses: actions/download-artifact@v4
        with:
          name: Graphics.c4g
      - uses: actions/download-artifact@v4
        with:
          name: c4group-Windows-x64

      - name: Create output directory
        run: New-Item -Path output -ItemType Directory

      - name: Create System.c4g update group
        run: autobuild/MakeEngineUpdateGroups.ps1 -GroupPath System.c4g -OutDir output
      - name: Create Graphics.c4g update group
        run: autobuild/MakeEngineUpdateGroups.ps1 -GroupPath Graphics.c4g -OutDir output

      - name: Publish System.c4g.c4u
        uses: actions/upload-artifact@v4
        with:
          name: System.c4g.c4u
          path: output/System.c4g.c4u

      - name: Publish Graphics.c4g.c4u
        uses: actions/upload-artifact@v4
        with:
          name: Graphics.c4g.c4u
          path: output/Graphics.c4g.c4u
