name: Release
on:
  push:
    tags:
      - '*'
    branches:
      - '*'

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-ci-config:
    name: Generate CI Configuration
    uses: './.github/workflows/ci-config.yml'

  build-binaries:
    name: Build Binaries
    needs: [generate-ci-config]
    uses: './.github/workflows/build.yml'
    with:
      matrix: ${{ needs.generate-ci-config.outputs.matrix }}

  build-content:
    name: Pack content groups
    runs-on: windows-latest
    needs: [generate-ci-config, build-binaries]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/content
          path: content

      - uses: actions/download-artifact@v4
        with:
          name: Windows-x64-c4group

  build-system-graphics-updates:
    name: "Update Groups: System.c4g & Graphics.c4g"
    runs-on: windows-latest
    needs: [generate-ci-config, build-binaries]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            autobuild

      - uses: actions/download-artifact@v4
        with:
          name: System.c4g
      - uses: actions/download-artifact@v4
        with:
          name: Graphics.c4g
      - uses: actions/download-artifact@v4
        with:
          name: Windows-x64-c4group

      - name: Create output directory
        run: New-Item -Path output -ItemType Directory
      - name: Set environment variables
        run: |
          "OBJVERSION=${{ needs.generate-ci-config.outputs.objversion }}" >> $Env:GITHUB_ENV
          "VERSION=${{ needs.generate-ci-config.outputs.buildversion }}" >> $Env:GITHUB_ENV
          "C4GROUP=./c4group.exe" >> $Env:GITHUB_ENV

      - name: Create System.c4g update group
        run: autobuild/MakeEngineUpdateGroups.ps1 -GroupPath System.c4g -OutDir output
      - name: Create Graphics.c4g update group
        run: autobuild/MakeEngineUpdateGroups.ps1 -GroupPath Graphics.c4g -OutDir output

      - name: Publish System.c4g
        uses: actions/upload-artifact@v4
        with:
          name: System.c4g
          path: output/System.c4g.c4u

      - name: Publish Graphics.c4g
        uses: actions/upload-artifact@v4
        with:
          name: Graphics.c4g
          path: output/Graphics.c4g.c4u
