name: Release
on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  build:
    uses: './.github/workflows/build.yml'

  build-content:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/content

      - uses: actions/download-artifact@v4
        with:
          name: Linux-x64-c4group
      - run: ls -R

